-- DDL & dummy Data insert
-- 테이블 및 시퀀스 삭제
DROP TABLE PERSON;
DROP TABLE JOB
DROP TABLE PERSON_PNO_SQ;

-- 테이블 및 시퀀스 생성
CREATE SEQUENCE PERSON_PNO_SQ;
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

CREATE TABLE JOB (
    jNO NUMBER(2) PRIMARY KEY,
    jNAME VARCHAR2(30)
);

CREATE TABLE PERSON(
    pNO NUMBER(5) PRIMARY KEY,
    pNAME VARCHAR2(30) NOT NULL,
    jNO NUMBER(2) REFERENCES JOB(jNO),
    KOR NUMBER(3) CHECK (KOR BETWEEN 0 AND 100),
    ENG NUMBER(3) CHECK (ENG BETWEEN 0 AND 100),
    MAT NUMBER(3) CHECK (MAT BETWEEN 0 AND 100)
);
    
-- DUMMY DATA
-- JOB (10,배우) (20,가수) (30, 엠씨)
-- PERSON 3명정도 INSERT
INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');
INSERT INTO JOB VALUES (30, '엠씨');

INSERT INTO PERSON VALUES (PERSON_PNO_SQ.NEXTVAL, '정우성', 10, 90, 80, 81);
INSERT INTO PERSON VALUES (PERSON_PNO_SQ.NEXTVAL, '박세영', 10, 80, 90, 80);
INSERT INTO PERSON VALUES (PERSON_PNO_SQ.NEXTVAL, '배수지', 20, 20, 90, 90);
