--[VIII] Sequence : 순차번호 생성기. 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 -- 1부터 시작한다(기본값 DEFAULT)
    INCREMENT BY 1 -- 1씩 증가(기본값 DEFAULT)
    MAXVALUE 9999 -- 최대값
    MINVALUE 1    -- 최소값
    NOCACHE
    NOCYCLE;
SELECT FRIEND_SEQ.NEXTVAL 
    FROM DUAL; -- 다음 순차번호 생성
SELECT FRIEND_SEQ.CURRVAL
    FROM DUAL;
-- EX1.FRIEND테이블 (NO1,2,3,4-PK, NAME, TEL, ADDRESS, LAST_MODIFY
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 99999
    NOCACHE 
    NOCYCLE;
CREATE TABLE FRIEND(
    NO      NUMBER(5),
    NAME    VARCHAR2(30) NOT NULL,
    TEL     VARCHAR2(20) UNIQUE, -- NULL 허용, NULL이 아닐땐 유일한 값
    ADDRESS VARCHAR2 (255),
    LAST_MODIFY DATE DEFAULT SYSDATE,
    PRIMARY KEY (NO)
    );
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL,'홍길동',NULL,'서울시 관악구'); -- 몇번이든 실행 가능
SELECT *
    FROM FRIEND;
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '박길동', '010-9999-9999', '서울'); --  NOT NULL 오류
SELECT *
    FROM FRIEND;
-- EX2.FRIEND테이블 (NO20240924001, 날짜002-PK, NAME, TEL, ADDRESS, LAST_MODIFY
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 999
    NOCACHE 
    NOCYCLE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO      NUMBER(11),
    NAME    VARCHAR2(30) NOT NULL,
    TEL     VARCHAR2(20) UNIQUE, -- NULL 허용, NULL이 아닐땐 유일한 값
    ADDRESS VARCHAR2 (255),
    LAST_MODIFY DATE DEFAULT SYSDATE,
    PRIMARY KEY (NO)
    );
SELECT TO_CHAR(SYSDATE,'YYYYMMDD')|| TRIM(TO_CHAR(FRIEND_SEQ.NEXTVAL,'000'))
    FROM DUAL;
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (TO_CHAR(SYSDATE,'YYYYMMDD')|| TRIM(TO_CHAR(FRIEND_SEQ.NEXTVAL,'000')),'홍길동',NULL,'서울시 관악구'); -- 몇번이든 실행 가능
    
SELECT *
    FROM FRIEND;

-- EX.1 
DROP SEQUENCE MEMBER;
DROP SEQUENCE MEMBER_SEQ;
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
CREATE SEQUENCE MEMBER_SEQ
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

CREATE TABLE MEMBER_LEVEL(
    LEVELNO   NUMBER (2),
    LEVELNAME VARCHAR2(50),
    PRIMARY KEY(LEVELNO)
);
CREATE TABLE MEMBER(
    mNO NUMBER(5),
    mNAME VARCHAR2(50),
    mPW VARCHAR2(8),
    mEMAIL VARCHAR2(50) UNIQUE,
    mPOINT NUMBER(5) CHECK(mPOINT >= 0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(2),
    PRIMARY KEY (mNO),
    FOREIGN KEY (LEVELNO) REFERENCES MEMBER_LEVEL (LEVELNO)
   ); 
INSERT INTO MEMBER_LEVEL
    VALUES (-1,'BALCK');
INSERT INTO MEMBER_LEVEL
    VALUES (0,'일반');
INSERT INTO MEMBER_LEVEL
    VALUES (1,'실버');
INSERT INTO MEMBER_LEVEL
    VALUES (2,'골드');

INSERT INTO MEMBER
    VALUES (MEMBER_SEQ.NEXTVAL,'홍길동','aa','HONG@HONG.COM',0,TO_DATE('22/03/10'),0);
INSERT INTO MEMBER
    VALUES (MEMBER_SEQ.NEXTVAL,'신길동','bb','SIN@SIN.COM',1000,TO_DATE('22/04/01'),1);


SELECT M.MNO NO, MNAME NAME, MRDATE "가입일" , MEMAIL EMAIL, MPOINT POINT, LEVELNAME||'고객' LEVELNAME 
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO = L.LEVELNO;
    


    